# Generated by Django 5.1.6 on 2025-03-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_contactus_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.IntegerField(verbose_name='Phone'),
        ),
    ]
