# Generated by Django 5.1.6 on 2025-03-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_user_token_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
    ]
