# Generated by Django 5.1.6 on 2025-03-06 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_user_alter_addtestimonial_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='modules.user'),
            preserve_default=False,
        ),
    ]
