# Generated by Django 5.1.6 on 2025-03-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_rename_user_portaluser_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtestimonial',
            name='type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
