# Generated by Django 5.1.6 on 2025-03-13 18:12

from django.db import migrations, models
import django.utils.timezone  

class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_addtestimonial_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtestimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addtestimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='addtestimonial',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
