# Generated by Django 5.1.6 on 2025-03-15 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_addtestimonial_created_at_addtestimonial_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtestimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AddCarasoulImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='carasoul')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carasoul', to='modules.portaluser')),
            ],
        ),
    ]
