# Generated by Django 5.1.6 on 2025-03-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_alter_addtestimonial_updated_at_addcarasoulimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUPImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='popupimage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popupimage', to='modules.portaluser')),
            ],
        ),
    ]
