# Generated by Django 5.1.6 on 2025-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_popupimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupimage',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popupimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
