# Generated by Django 5.1.6 on 2025-03-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_visionmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionmission',
            name='text',
            field=models.TextField(),
        ),
    ]
