# Generated by Django 5.1.6 on 2025-03-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_facilities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilities',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='facilities',
            name='order',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
